import { accessSync, constants, existsSync, statSync } from 'node:fs';
import { rename } from 'node:fs/promises';
import path from 'node:path';
import { AppError } from '../../errors';
import { config } from '../../config';
import { isUniqueViolation, unusedId } from '../../db/constraints';
import { Logger } from '../../logger';
import { DEFAULT_LIBRARY_SETTINGS, type CreateLibraryRequest, type Library, type UpdateLibraryRequest } from '../../schemas/libraries';
import { deleteDataDirectory, deleteEmptyBinFolder } from '../../utils/deletions';
import { ensureDir } from '../../utils/files';
import { inferredLibraryName } from '../../utils/library_name';
import { containsPath, getBinPath, getDataPath } from '../../utils/paths';
import { renditionVariants } from '../processing/renditions/renditions';
import type { PhotoPathsRepository } from '../photos/paths/photo_paths_repository';
import type { PhotoScanRepository } from '../photos/scan/photo_scan_repository';
import { libraryMutex } from '../sync/coordination/library_mutex';
import { ensureBinFolder } from './bin_folder';
import type { LibrariesRepository } from './libraries_repository';

const log = new Logger('libraries');

export interface LibraryLifecycleListener {
  onLibraryCreated(library: Library): void;
  onLibraryDeleted(libraryId: string): void;
  /** For listeners holding something derived from the library's settings. */
  onLibraryUpdated?(library: Library): void;
}

// Removing a library takes its generated files with it: renditions are keyed by
// photo id, and ids are minted per insert, so re-adding the same folder can
// never reuse them. Left behind they are dead weight nothing will ever claim.
//
// `deleteDataDirectory`'s originals check stays as an assertion rather than as a
// trigger for anything: nothing under `DATA_DIR` is generated by anyone but us
// (§6), and `rm -rf` is the one call here that cannot be undone.
async function removeDataDirectory(library: Library): Promise<void> {
  const dataPath = getDataPath(library);
  try {
    await deleteDataDirectory(dataPath);
  } catch (err) {
    log.error('could not remove the data directory', { dataPath, err });
  }
}

// Both directions, because `removeDataDirectory` deletes recursively: a library
// root inside `DATA_DIR` is the one that loses photographs (§6). Checked at
// creation and at startup, since `DATA_DIR` is an environment variable that can
// change under a catalogue that was already valid.
export function assertNoDataDirectoryOverlap(rootPath: string): void {
  if (containsPath(config.dataDir, rootPath)) {
    throw new Error(`library root ${rootPath} is inside DATA_DIR (${config.dataDir}); removing that library would delete it`);
  }
  if (containsPath(rootPath, config.dataDir)) {
    throw new Error(`DATA_DIR (${config.dataDir}) is inside library root ${rootPath}; generated files must live outside it`);
  }
}

// One mechanism, and it writes nothing: a real write test would put a file in a
// folder the photographer may have asked us never to touch (§4.1). `access` can
// be fooled by an exotic ACL, but a root where it lies is the same case as a
// volume remounted read-only later, which already surfaces as an `IO_ERROR` from
// the write that fails.
export function isWritable(dir: string): boolean {
  try {
    accessSync(dir, constants.W_OK);
    return true;
  } catch {
    return false;
  }
}

export class LibrariesService {
  private readonly listeners: LibraryLifecycleListener[] = [];

  constructor(
    private readonly repo: LibrariesRepository,
    private readonly photoScan: PhotoScanRepository,
    private readonly photoPaths: PhotoPathsRepository,
  ) {}

  addLifecycleListener(listener: LibraryLifecycleListener): void {
    this.listeners.push(listener);
  }

  /**
   * Announces a library this service did not create (§9.1).
   *
   * A replica is inserted by the replication runner - it carries the remote's id
   * and skips the genesis walk, neither of which `create` can do - and everything
   * that hangs off a library appearing still has to hear about it. The watcher
   * especially: its update path returns early for a library it has never been
   * told about, so one that misses this can never acquire a watcher at all.
   */
  announceCreated(library: Library): void {
    // Independent subscribers to one fact, so one failing is not the next one's
    // business - and the watcher is registered last, so a loop that stops at the
    // first throw is a loop that leaves the library unwatched. Same reasoning as
    // the deletion side below.
    for (const listener of this.listeners) {
      try {
        listener.onLibraryCreated(library);
      } catch (err) {
        log.error('a listener failed on a new library', { library: library.id, err });
      }
    }
  }

  async create(request: CreateLibraryRequest): Promise<Library> {
    if (!existsSync(request.root_path) || !statSync(request.root_path).isDirectory()) {
      throw new AppError('VALIDATION_ERROR', `root_path does not exist or is not a directory: ${request.root_path}`);
    }
    if (this.repo.getByRootPath(request.root_path)) {
      throw new AppError('CONFLICT', `library root already registered: ${request.root_path}`);
    }
    try {
      assertNoDataDirectoryOverlap(request.root_path);
    } catch (err) {
      throw new AppError('VALIDATION_ERROR', (err as Error).message);
    }
    // Refused rather than silently upgraded: the client supplied a `bin_name`
    // assuming the root was writable, so it asked for something this root cannot
    // do (§4.1).
    if (!request.read_only && !isWritable(request.root_path)) {
      throw new AppError('READ_ONLY', `${request.root_path} is not writable; add it as a read-only library`);
    }
    // A bin is a folder the app makes under the root, which is exactly what the
    // flag forbids.
    const binName = request.read_only ? null : request.bin_name;
    // The one combination the columns must never hold (§4.1): a writable library
    // with no bin bins in place, silently, in a catalogue whose photographer was
    // shown a bin-name field. Refused here rather than defaulted, because a
    // client that sent null meant something by it.
    if (!request.read_only && binName == null) {
      throw new AppError('VALIDATION_ERROR', 'a writable library needs a bin_name; send read_only to have no bin folder');
    }
    // A folder already sitting at that name is adopted rather than refused
    // (§12.3): the bin channel walks it on the first sync and imports what it
    // holds as already-binned, so nothing inside is dropped in silence. The Add
    // dialog says so before the create; here it is only worth a line in the log.
    //
    // A *file* of that name is refused, and refused here: `mkdir` would fail on
    // it several steps later, by which point the data directory has been made
    // and there is no library row to ever prune it against.
    const binPath = binName == null ? null : path.join(request.root_path, binName);
    const occupant = binPath == null ? null : statSync(binPath, { throwIfNoEntry: false });
    if (occupant != null && !occupant.isDirectory()) {
      throw new AppError('VALIDATION_ERROR', `${binPath} is a file, not a folder: choose another bin folder name`);
    }
    const adopted = occupant != null;
    if (adopted) log.info('the bin folder was already there and is adopted', { root: request.root_path, bin: binName });

    const library: Library = {
      // Settled here rather than redrawn at the insert: the rendition directories
      // and the bin below are made under this id, and a later draw would leave them.
      id: unusedId((candidate) => this.repo.getById(candidate) != null),
      root_path: request.root_path,
      bin_name: binName,
      read_only: request.read_only,
      name: request.name == null || request.name === '' ? inferredLibraryName(request.root_path) : request.name,
      ordering: request.ordering,
      ...DEFAULT_LIBRARY_SETTINGS,
      rendition_source: request.rendition_source,
      auto_stack: request.auto_stack,
      include_subfolders: request.include_subfolders,
      include_non_raw: request.include_non_raw,
      last_synced_at: null,
      photo_count: 0,
    };

    // Every directory a rendition can land in, up front, so a library that has
    // not built anything yet still has somewhere for the orphan sweep to look
    // and for a reader to go and see. Not the thing that makes a build work:
    // `ensureOutputDirs` in the processing worker creates its own outputs' parents
    // before every job, because a rendition added later would otherwise need
    // remembering in two places.
    const dataPath = getDataPath(library);
    for (const variant of renditionVariants()) await ensureDir(path.join(dataPath, 'renditions', variant));

    // The bin exists from the moment the library does (§12.3), in the order
    // `ShootsService.create` uses: made, stat'ed, then the row inserted.
    const bin = binName == null ? null : await this.makeBinFolder(library);

    try {
      this.repo.insert({ ...library, identity: bin?.identity });
    } catch (err) {
      // Only the one this create made: an adopted folder is the photographer's,
      // and a failed insert is no reason to take an empty one of theirs away.
      if (bin != null && !adopted) {
        await deleteEmptyBinFolder(library, bin.path).catch((e: unknown) =>
          log.error('could not remove the bin folder a failed create left behind', { path: bin.path, err: e }),
        );
      }
      // getByRootPath above catches the common case; a concurrent create with the
      // same root_path can still pass it before either commits and hit UNIQUE here.
      if (isUniqueViolation(err)) throw new AppError('CONFLICT', `library root already registered: ${request.root_path}`);
      throw err;
    }
    log.info('library created', { library: library.id, root: library.root_path, data: dataPath, readOnly: library.read_only });
    this.announceCreated(library);
    return library;
  }

  // Creation's own bin step, which cannot go through `ensureBinFolder`: the row
  // does not exist yet, so there is nothing to write the identity to. The
  // identity rides into the INSERT instead.
  private async makeBinFolder(library: Library): Promise<{ path: string; identity: { dev: number | null; ino: number | null; birthtime: number | null } }> {
    const bin = getBinPath(library)!;
    await ensureDir(bin);
    const stats = statSync(bin, { throwIfNoEntry: false });
    return {
      path: bin,
      identity: { dev: stats?.dev ?? null, ino: stats?.ino ?? null, birthtime: stats?.birthtimeMs ?? null },
    };
  }

  get(libraryId: string): Library {
    const library = this.repo.getById(libraryId);
    if (!library) throw new AppError('NOT_FOUND', `library not found: ${libraryId}`);
    return library;
  }

  list(): Library[] {
    return this.repo.list();
  }

  // A partial update: the settings UI changes one control at a time, and every
  // field left out keeps its stored value. Changing a rendition setting does not
  // touch existing photos - it is the default for what gets built next, and for
  // an explicit rebuild (§10.2).
  async update(libraryId: string, updates: UpdateLibraryRequest): Promise<Library> {
    const current = this.repo.getById(libraryId);
    if (current == null) throw new AppError('NOT_FOUND', `library not found: ${libraryId}`);
    // Before anything is written. `read_only` and `bin_name` are applied in that
    // order, so a request asking to set the flag *and* rename would commit the
    // flag and then refuse the rename against it - a 403 saying nothing happened,
    // over a library that is now read-only.
    if (updates.read_only === true && updates.bin_name != null && !current.read_only) {
      throw new AppError('VALIDATION_ERROR', 'a library cannot be made read-only and have its bin renamed in one request');
    }
    // Both of these touch the tree, so both go first and under the mutex, before
    // anything that only writes a column.
    if (updates.read_only != null && updates.read_only !== current.read_only) {
      await this.setReadOnly(current, updates.read_only, updates.bin_name);
    }
    // Skipped when clearing the flag just made a bin of that name: `setReadOnly`
    // has already written it, so this would be a no-op rename at best.
    const renamed = this.get(libraryId);
    if (updates.bin_name != null && updates.bin_name !== renamed.bin_name) await this.renameBin(renamed, updates.bin_name);
    if (updates.name != null) this.repo.setName(libraryId, updates.name);
    if (updates.ordering != null) this.repo.setOrdering(libraryId, updates.ordering);
    if (updates.rendition_source != null) this.repo.setRenditionSource(libraryId, updates.rendition_source);
    if (updates.rendition_hdr != null) this.repo.setRenditionHdr(libraryId, updates.rendition_hdr);
    if (updates.render_skip_full != null) this.repo.setRenderSkip(libraryId, 'full', updates.render_skip_full);
    if (updates.render_skip_max != null) this.repo.setRenderSkip(libraryId, 'max', updates.render_skip_max);
    if (updates.include_subfolders != null) this.repo.setIncludeSubfolders(libraryId, updates.include_subfolders);
    if (updates.include_non_raw != null) this.repo.setIncludeNonRaw(libraryId, updates.include_non_raw);
    if (updates.auto_stack != null) this.repo.setAutoStack(libraryId, updates.auto_stack);
    if (updates.auto_stack_similarity != null) this.repo.setAutoStackSimilarity(libraryId, updates.auto_stack_similarity);
    if (updates.auto_stack_window_seconds != null) this.repo.setAutoStackWindow(libraryId, updates.auto_stack_window_seconds);
    const updated = this.get(libraryId);
    // The watcher holds a scope built from these, so an excluded folder - or a
    // renamed bin, which it would otherwise keep in its ignore list under the old
    // name and then watch under the new one (§4.1) - would keep waking syncs
    // until a restart.
    for (const listener of this.listeners) listener.onLibraryUpdated?.(updated);
    return updated;
  }

  // **Setting it** keeps `bin_name` and moves nothing: new binnings are in place
  // from that point (§12.1), and the bin channel goes on reconciling the folder that
  // is already there, so the photographer can manage it by hand.
  //
  // **Clearing it** on a library with no bin needs one named in the same request,
  // and makes the folder exactly as creation does. A flipped library already has
  // both, so clearing its flag creates nothing and re-stats nothing - and the
  // "a folder of that name already exists" refusal does not apply to it, since a
  // library that already owns that folder is not colliding with anything.
  private async setReadOnly(library: Library, readOnly: boolean, binName: string | undefined): Promise<void> {
    if (readOnly) {
      this.repo.setReadOnly(library.id, true);
      return;
    }
    if (!isWritable(library.root_path)) {
      throw new AppError('READ_ONLY', `${library.root_path} is still not writable`);
    }
    if (library.bin_name != null) {
      this.repo.setReadOnly(library.id, false);
      return;
    }
    if (binName == null) {
      throw new AppError('VALIDATION_ERROR', 'clearing read_only needs a bin_name: the library has no bin folder yet');
    }
    if (existsSync(path.join(library.root_path, binName))) {
      throw new AppError('CONFLICT', `a folder named "${binName}" already exists at ${library.root_path}`);
    }

    await libraryMutex.run(library.id, async () => {
      this.repo.setBinName(library.id, binName);
      this.repo.setReadOnly(library.id, false);
      try {
        await ensureBinFolder(this.get(library.id), this.repo);
      } catch (err) {
        this.repo.setBinName(library.id, null);
        this.repo.setReadOnly(library.id, true);
        throw err;
      }
    });
  }

  // Renaming the bin **moves the folder**. DESIGN §4.1 refused this because it
  // would "strand every already-binned RAW in a folder the scan would then walk
  // straight back in" - an argument against changing the setting *alone*.
  // Changing it and moving the folder together strands nothing.
  private async renameBin(library: Library, binName: string): Promise<void> {
    if (library.bin_name === binName) return; // a no-op, not a rename
    if (library.read_only) {
      // First, so a read-only library never sees CONFLICT.
      throw new AppError('READ_ONLY', `${library.name} is read-only; clear the flag before renaming its bin folder`);
    }
    if (library.bin_name == null) {
      throw new AppError('VALIDATION_ERROR', 'this library has no bin folder; clear read_only in the same request to make one');
    }

    const from = getBinPath(library)!;
    const to = path.join(library.root_path, binName);
    const identity = this.repo.getBinIdentity(library.id);
    // On a case-insensitive filesystem `existsSync(<root>/bin)` is true when the
    // folder is `Bin`, so a case-only rename has to compare inodes rather than
    // collide with itself. Advisory anyway: POSIX `rename` onto an existing empty
    // directory removes it, so a folder appearing in the window is a race, bounded
    // by `libraryMutex` on our own side.
    const occupant = statSync(to, { throwIfNoEntry: false });
    if (occupant != null && !(occupant.dev === identity?.dev && occupant.ino === identity?.ino)) {
      throw new AppError('CONFLICT', `a folder named "${binName}" already exists at ${library.root_path}`);
    }

    await libraryMutex.run(library.id, async () => {
      // The rename goes first, and outside any transaction - a filesystem
      // operation has no commit to join. A crash between it and the commit leaves
      // disk at the new name with stale columns, which is exactly what §9.1.1
      // follows; committing first would leave the mirror image, and §9.1.1 would
      // follow the *old* folder and revert the name just set.
      try {
        // Same parent directory, so EXDEV is impossible and no copy fallback is
        // needed - this is not `moveIntoDir`, which exists to suffix colliding files.
        await rename(from, to);
      } catch (err) {
        const code = (err as NodeJS.ErrnoException).code;
        if (code === 'ENOENT') {
          // Recreating is right for a deleted folder and wrong for a moved one,
          // where it would orphan the real bin and leave §9.1.1 to adopt the orphan
          // and revert the name just set. A full sync distinguishes them (§12.3).
          throw new AppError('IO_ERROR', `the bin folder is not at ${from}: run a full sync, then retry`);
        }
        if (code === 'EBUSY' || code === 'EPERM') {
          throw new AppError('IO_ERROR', `could not move ${from}: it may be a mount point, or open elsewhere`);
        }
        throw err;
      }

      this.photoScan.transaction(() => {
        this.repo.setBinName(library.id, binName);
        // `deleted_from_path` records where the photograph came from, outside the
        // bin, which has not moved.
        this.photoPaths.rewriteBinnedPathPrefix(library.id, library.bin_name!, binName);
      });
      // bin_dev/bin_ino/bin_birthtime are left alone: `rename` preserves the inode.
      log.info('bin folder renamed', { library: library.id, from, to });
    });
  }

  async delete(libraryId: string): Promise<void> {
    // Read before the row goes: the data directory's location lives on it.
    const library = this.repo.getById(libraryId);
    if (!this.repo.delete(libraryId)) {
      throw new AppError('NOT_FOUND', `library not found: ${libraryId}`);
    }
    log.info('library deleted', { library: libraryId, root: library?.root_path });
    // One listener's failure is not the next one's business. They are independent
    // subscribers to the same fact - a watcher to unsubscribe, replication to drop
    // the state no foreign key reaches - and a loop that stops at the first throw
    // leaks whatever the rest of them would have released.
    for (const listener of this.listeners) {
      try {
        listener.onLibraryDeleted(libraryId);
      } catch (err) {
        log.error('a listener failed on a deleted library', { library: libraryId, err });
      }
    }
    if (library != null) await removeDataDirectory(library);
  }
}
