import { existsSync, statSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { AppError } from '../../errors';
import { config } from '../../config';
import { isUniqueViolation } from '../../db/constraints';
import { Logger } from '../../logger';
import { DEFAULT_LIBRARY_SETTINGS, type CreateLibraryRequest, type Library, type UpdateLibraryRequest } from '../../schemas/libraries';
import { deleteDataDirectory } from '../../utils/deletions';
import { ensureDir } from '../../utils/files';
import { inferredLibraryName } from '../../utils/library_name';
import { containsPath, getDataPath } from '../../utils/paths';
import { renditionDirs } from '../processing/renditions';
import type { LibrariesRepository } from './libraries_repository';

const log = new Logger('libraries');

export interface LibraryLifecycleListener {
  onLibraryCreated(library: Library): void;
  onLibraryDeleted(libraryId: string): void;
  /** For listeners holding something derived from the library's settings. */
  onLibraryUpdated?(library: Library): void;
}

// Removing a library takes its generated files with it: renditions are keyed by
// photo id, and ids are minted per insert, so re-adding the same folder can
// never reuse them. Left behind they are dead weight nothing will ever claim.
//
// `deleteDataDirectory`'s originals check stays as an assertion rather than as a
// trigger for anything: nothing under `DATA_DIR` is generated by anyone but us
// (§3), and `rm -rf` is the one call here that cannot be undone.
async function removeDataDirectory(library: Library): Promise<void> {
  const dataPath = getDataPath(library);
  try {
    await deleteDataDirectory(dataPath);
  } catch (err) {
    log.error('could not remove the data directory', { dataPath, err });
  }
}

// Both directions, because `removeDataDirectory` deletes recursively: a library
// root inside `DATA_DIR` is the one that loses photographs (§3.1). Checked at
// creation and at startup, since `DATA_DIR` is an environment variable that can
// change under a catalogue that was already valid.
export function assertNoDataDirectoryOverlap(rootPath: string): void {
  if (containsPath(config.dataDir, rootPath)) {
    throw new Error(`library root ${rootPath} is inside DATA_DIR (${config.dataDir}); removing that library would delete it`);
  }
  if (containsPath(rootPath, config.dataDir)) {
    throw new Error(`DATA_DIR (${config.dataDir}) is inside library root ${rootPath}; generated files must live outside it`);
  }
}

export class LibrariesService {
  private readonly listeners: LibraryLifecycleListener[] = [];

  constructor(private readonly repo: LibrariesRepository) {}

  addLifecycleListener(listener: LibraryLifecycleListener): void {
    this.listeners.push(listener);
  }

  async create(request: CreateLibraryRequest): Promise<Library> {
    if (!existsSync(request.root_path) || !statSync(request.root_path).isDirectory()) {
      throw new AppError('VALIDATION_ERROR', `root_path does not exist or is not a directory: ${request.root_path}`);
    }
    if (this.repo.getByRootPath(request.root_path)) {
      throw new AppError('CONFLICT', `library root already registered: ${request.root_path}`);
    }
    try {
      assertNoDataDirectoryOverlap(request.root_path);
    } catch (err) {
      throw new AppError('VALIDATION_ERROR', (err as Error).message);
    }
    // The scan skips whatever is at this path sight unseen (§12.3), so adopting a
    // folder the user already keeps there would drop everything inside from the
    // import without saying so. Asked for a different name instead, which is why
    // the name is a field on the create form at all.
    if (existsSync(path.join(request.root_path, request.bin_name))) {
      throw new AppError(
        'VALIDATION_ERROR',
        `a folder named "${request.bin_name}" already exists at ${request.root_path}: choose another bin folder name, or the photographs inside it would never be imported`,
      );
    }

    const library: Library = {
      id: randomUUID(),
      root_path: request.root_path,
      bin_name: request.bin_name,
      name: request.name == null || request.name === '' ? inferredLibraryName(request.root_path) : request.name,
      ordering: request.ordering,
      ...DEFAULT_LIBRARY_SETTINGS,
      include_subfolders: request.include_subfolders,
      // A shoot is a subfolder, so mirroring folders the scan will never reach
      // would only ever produce nothing (§4.1).
      mirror_shoots: request.include_subfolders && request.mirror_shoots,
      last_synced_at: null,
      photo_count: 0,
    };

    // Every directory a rendition can land in, up front: nothing is created
    // lazily by a writer, so a build is a write and not a mkdir-then-write.
    const dataPath = getDataPath(library);
    for (const dir of renditionDirs()) await ensureDir(path.join(dataPath, 'renditions', dir));

    try {
      this.repo.insert(library);
    } catch (err) {
      // getByRootPath above catches the common case; a concurrent create with the
      // same root_path can still pass it before either commits and hit UNIQUE here.
      if (isUniqueViolation(err)) throw new AppError('CONFLICT', `library root already registered: ${request.root_path}`);
      throw err;
    }
    log.info('library created', { library: library.id, root: library.root_path, data: dataPath });
    for (const listener of this.listeners) listener.onLibraryCreated(library);
    return library;
  }

  get(libraryId: string): Library {
    const library = this.repo.getById(libraryId);
    if (!library) throw new AppError('NOT_FOUND', `library not found: ${libraryId}`);
    return library;
  }

  list(): Library[] {
    return this.repo.list();
  }

  // A partial update: the settings UI changes one control at a time, and every
  // field left out keeps its stored value. Changing a rendition setting does not
  // touch existing photos - it is the default for what gets built next, and for
  // an explicit rebuild (§10.2).
  update(libraryId: string, updates: UpdateLibraryRequest): Library {
    const current = this.repo.getById(libraryId);
    if (current == null) throw new AppError('NOT_FOUND', `library not found: ${libraryId}`);
    if (updates.name != null) this.repo.setName(libraryId, updates.name);
    if (updates.ordering != null) this.repo.setOrdering(libraryId, updates.ordering);
    if (updates.rendition_source != null) this.repo.setRenditionSource(libraryId, updates.rendition_source);
    if (updates.rendition_hdr != null) this.repo.setRenditionHdr(libraryId, updates.rendition_hdr);
    if (updates.include_subfolders != null) this.repo.setIncludeSubfolders(libraryId, updates.include_subfolders);
    // Mirroring folders the scan will never reach produces nothing, so the two
    // settings cannot be left disagreeing - whichever of them this request moved.
    const includeSubfolders = updates.include_subfolders ?? current.include_subfolders;
    const mirror = updates.mirror_shoots ?? current.mirror_shoots;
    if (mirror !== current.mirror_shoots || !includeSubfolders) {
      this.repo.setMirrorShoots(libraryId, includeSubfolders && mirror);
    }
    if (updates.auto_stack != null) this.repo.setAutoStack(libraryId, updates.auto_stack);
    if (updates.auto_stack_similarity != null) this.repo.setAutoStackSimilarity(libraryId, updates.auto_stack_similarity);
    if (updates.auto_stack_window_seconds != null) this.repo.setAutoStackWindow(libraryId, updates.auto_stack_window_seconds);
    const updated = this.get(libraryId);
    // The watcher holds a scope built from these, so an excluded folder would
    // otherwise keep waking syncs until a restart.
    for (const listener of this.listeners) listener.onLibraryUpdated?.(updated);
    return updated;
  }

  async delete(libraryId: string): Promise<void> {
    // Read before the row goes: the data directory's location lives on it.
    const library = this.repo.getById(libraryId);
    if (!this.repo.delete(libraryId)) {
      throw new AppError('NOT_FOUND', `library not found: ${libraryId}`);
    }
    log.info('library deleted', { library: libraryId, root: library?.root_path });
    for (const listener of this.listeners) listener.onLibraryDeleted(libraryId);
    if (library != null) await removeDataDirectory(library);
  }
}
