export const BackupStrings = {
  heading: () => 'Backup',
  noFolder: () => 'Copy every original to a folder, drive, or share.',
  folderLabel: () => 'Backup folder',
  folderPlaceholder: () => '/Volumes/NAS/Photos',
  confirmFolder: () => 'Use this backup folder?',
  confirmFolderBody: (path: string) => `Confirm that ${path} is the backup folder you want to use for this library.`,
  useFolder: () => 'Use folder',
  backingUp: () => 'Backing up…',
  operationBusy: () => 'Wait for the backup operation to finish.',
  remove: () => 'Remove backup',
  removeTitle: (name: string) => `Remove backup folder "${name}"?`,
  removeKeepsFiles: () => 'Every file already on the backup stays there.',
  removeStrandsPhotos: (count: number) =>
    `${count} ${count === 1 ? 'original has' : 'originals have'} no local copy on this device. Restore ${count === 1 ? 'it' : 'them'} before removing this backup, or keep access to another surviving copy.`,
  removeMissingOriginals: (count: number) =>
    `We couldn't find ${count} ${count === 1 ? 'original' : 'originals'} on this device or this backup. Removing the backup doesn't restore ${count === 1 ? 'it' : 'them'}. Look for another copy before removing it.`,
  fetchAndRemove: () => 'Fetch and remove',
  removeWithoutFetching: () => 'Remove without fetching',
  fetching: () => 'Restoring…',
  preparingFetch: () => 'Finding originals to restore…',
  fetchedOf: (done: number, total: number) => `${done} of ${total} ${total === 1 ? 'original' : 'originals'} restored`,
  fetchingFile: (path: string, percent: number) => `${path} · ${percent}%`,
  restoreFailed: (count: number) => `We couldn't restore ${count} ${count === 1 ? 'original' : 'originals'}.`,
  restorePaused: (count: number) => `Restoring ${count} ${count === 1 ? 'original' : 'originals'} is paused.`,
  restoreCancelled: (count: number) => `Restoring ${count} ${count === 1 ? 'original' : 'originals'} was cancelled.`,
  storageLimit: () => 'Local storage limit',
  gigabytes: () => 'GB',
  storageLimitHint: () => 'Above this limit, local copies used least recently can be removed after their backup copies are checked.',
  storageLimitReadOnly: () => "Read-only libraries can't remove local originals.",
};
