// Holding behaviour to a recorded copy of it.
//
// Both pins here were generated by the TypeScript this subsystem replaced, so they
// are a regression net rather than an independent oracle: they say "nothing changed",
// not "this is correct". Correctness is what the other tests and a real HDR display
// are for. Regenerate deliberately, never to make a red test green:
//
//   BOWERBIRD_UPDATE_PINS=1 cargo test --manifest-path native/rawshim/Cargo.toml \
//       --features fixtures

use std::path::PathBuf;

fn path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../test/fixtures").join(name)
}

/// Compares `actual` against the recorded copy in `name`, row by row.
///
/// Row by row rather than whole: a diff of two 120-line blobs names nothing useful,
/// and the first differing row is what a reader actually needs.
pub fn check(name: &str, actual: &str) {
    let path = path(name);
    if std::env::var("BOWERBIRD_UPDATE_PINS").is_ok_and(|v| v == "1") {
        std::fs::write(&path, actual).expect("could not write the pin");
        return;
    }
    let expected = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read {}: {e}", path.display()));
    let want: Vec<&str> = expected.trim_end().split('\n').collect();
    let got: Vec<&str> = actual.trim_end().split('\n').collect();
    for i in 0..want.len().max(got.len()) {
        assert_eq!(
            got.get(i).copied().unwrap_or("<missing>"),
            want.get(i).copied().unwrap_or("<unexpected>"),
            "row {} of {}",
            i + 1,
            path.display(),
        );
    }
}
