// Holding behaviour to a recorded copy of it.
//
// Both pins here were generated by the TypeScript this subsystem replaced, so they
// are a regression net rather than an independent oracle: they say "nothing changed",
// not "this is correct". Correctness is what the other tests and a real HDR display
// are for.
//
// `hdr_grade.pin.txt` is the exception and is worth more than it looks. It was regenerated
// from the per-pixel Rust grade at the moment that implementation was removed, so it is a
// frozen record of what the CPU produced - and the GPU has had to match it ever since,
// within `check_within`'s tolerance, on a real 3840px photo. That is a better oracle than
// a second live implementation was: it cannot drift, and nobody has to keep it in step.
// Regenerating it is therefore a bigger claim than regenerating the others.
//
// Regenerate deliberately, never to make a red test green:
//
//   BOWERBIRD_UPDATE_PINS=1 cargo test --manifest-path native/rawshim/Cargo.toml \
//       --features fixtures

use std::path::PathBuf;

fn path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../test/fixtures").join(name)
}

/// Compares `actual` against the recorded copy in `name`, row by row.
///
/// Row by row rather than whole: a diff of two 120-line blobs names nothing useful,
/// and the first differing row is what a reader actually needs.
pub fn check(name: &str, actual: &str) {
    check_within(name, actual, 0.0);
}

/// The same, with numbers compared to `epsilon` rather than as text.
///
/// **For output a GPU produced, which cannot be pinned exactly and should not be.** SPIR-V
/// gives transcendentals a relaxed precision - `pow`, which the PQ and sRGB transfers both
/// use, is allowed several ULP and vendors differ - texture filtering may be a fixed-point
/// approximation of the weights, which is what the lattice lookup is, and FMA contraction
/// is the compiler's choice. So RADV, NVIDIA, Intel and a software adapter each produce
/// slightly different bytes for the same grade, and so can one driver update. A hash of
/// them pins the machine that generated it, not the picture.
///
/// Token by token, so a row states its own units: anything that parses as a number is
/// compared numerically, anything else - a label, a `96x64` - has to match exactly. A
/// changed sample count or a renamed row is still a failure.
pub fn check_within(name: &str, actual: &str, epsilon: f64) {
    let path = path(name);
    if std::env::var("BOWERBIRD_UPDATE_PINS").is_ok_and(|v| v == "1") {
        std::fs::write(&path, actual).expect("could not write the pin");
        return;
    }
    let expected = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read {}: {e}", path.display()));
    let want: Vec<&str> = expected.trim_end().split('\n').collect();
    let got: Vec<&str> = actual.trim_end().split('\n').collect();
    for i in 0..want.len().max(got.len()) {
        let (a, b) = (
            got.get(i).copied().unwrap_or("<missing>"),
            want.get(i).copied().unwrap_or("<unexpected>"),
        );
        if a == b {
            continue;
        }
        let split = |row: &str| -> Vec<String> {
            row.split(|c: char| c == '\t' || c == ' ' || c == ',' || c == '/')
                .map(str::to_owned)
                .collect()
        };
        let (at, bt) = (split(a), split(b));
        let near = at.len() == bt.len()
            && at.iter().zip(&bt).all(|(x, y)| match (x.parse::<f64>(), y.parse::<f64>()) {
                (Ok(x), Ok(y)) => (x - y).abs() <= epsilon,
                _ => x == y,
            });
        assert!(near, "row {} of {}\n  got  {a}\n  want {b}", i + 1, path.display());
    }
}
