// The sidebar names destinations, and a destination owns its own name: everything the
// links here read is imported from the page they lead to.
export const AppStrings = {
  addALibrary: () => 'Add library',
  photos: () => 'Photos',
  editsToChoose: () => 'Edits to choose',
  notSyncing: () => 'Not syncing',
  brand: () => 'Bowerbird',
  sidebar: () => 'Sidebar',
  hideSidebar: () => 'Hide sidebar',
  resizeSidebar: () => 'Resize sidebar',
  /** A sidebar row read aloud: its name, and how many photographs are behind it. */
  rowHolding: (name: string, photoCount: number) => `${name}, ${photoCount} ${photoCount === 1 ? 'photo' : 'photos'}`,
  readOnly: () => 'Read-only',
  readOnlyName: (name: string) => `${name}, read-only`,
  catalogue: () => 'Catalogue',
  shortcuts: () => 'Shortcuts',
  keyboardShortcuts: () => 'Keyboard shortcuts',

  keysArrows: () => '← → ↑ ↓',
  keysRatings: () => '0 – 5',
  keysDelete: () => 'Del',
  keysSpace: () => 'Space',
  keysEnter: () => 'Enter',
  keysZoom: () => '+ / −',
  keysEscape: () => 'Esc',
  keysSides: () => '← →',
  keysDownOrSpace: () => '↓ / Space',
  keysPeek: () => 'Shift (hold)',
  keysUndo: () => '⌘Z / Backspace',
  keysUpDown: () => '↑ ↓',
  keysOpenClose: () => '→ ←',
  keysHomeEnd: () => 'Home / End',

  shortcutMoveBetweenPhotos: () => 'Move between photos',
  shortcutSetRating: () => 'Set rating',
  shortcutPickOrClear: () => 'Pick / clear',
  shortcutAddToSelection: () => 'Add to selection',
  shortcutOpenPhoto: () => 'Open the photo or stack',
  shortcutFullscreen: () => 'Fullscreen (photo view)',
  shortcutZoom: () => 'Zoom in a stop / back to fitted (photo view)',
  shortcutShowCameraJpeg: () => "Show embedded JPEG (photo viewer)",
  shortcutShowRendition: () => 'Show RAW rendition (photo viewer)',
  shortcutToggleFilmstrip: () => 'Show / hide the filmstrip (photo viewer)',
  shortcutToggleInfo: () => 'Show / hide photo info (photo viewer)',
  shortcutMoreActions: () => 'Open / close the more actions menu',
  shortcutClearOrLeave: () => 'Clear selection, or leave a photo',
  shortcutPreferSide: () => 'Prefer the left / right photo (Triage stack)',
  shortcutPickBoth: () => 'Pick both (Triage stack)',
  shortcutPeek: () => 'Peek at the other photo (Triage stack, Flip)',
  shortcutUndoRound: () => 'Undo the last round (Triage stack)',
  shortcutSwitchPresentation: () => 'Switch Flip and Split (Triage stack)',
  shortcutMoveBetweenFolders: () => 'Move between folders (Shoots)',
  shortcutOpenCloseFolder: () => 'Open / close a folder (Shoots)',
  shortcutFirstLastFolder: () => 'First / last folder (Shoots)',
};
