// Builds the browser's AV1 decoder (`native/avif_planes`) into `native/rawshim/pkg`, beside the
// module it is shipped with, under a content-addressed name for the reason `hash-pkg.ts` gives.
//
// `wasm32-wasip1-threads` rather than `wasm32-unknown-unknown`: rav1d reaches for `libc` types the
// latter has no definition of, and threads are what make a 24MP still take tens of milliseconds
// rather than seconds. The page supplies the threads itself (`web/src/avif/avif_pool.ts`).

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const TARGET = 'wasm32-wasip1-threads';
const manifest = join(ROOT, 'native', 'avif_planes', 'Cargo.toml');
const built = join(ROOT, 'native', 'avif_planes', 'target', TARGET, 'release', 'avif_planes.wasm');
const pkg = join(ROOT, 'native', 'rawshim', 'pkg');
const forwards = '// Generated by scripts/build-avif-planes.ts.';

const RUSTFLAGS = [
  '-C target-feature=+simd128',
  '-C link-arg=--max-memory=1073741824',
  // A thread's entry, and the two initialisers a reactor module would run from `_initialize`:
  // this one links none, so without them the first `thread::spawn` waits on a thread record
  // nothing ever wrote.
  '-C link-arg=--export=wasi_thread_start',
  '-C link-arg=--export=__wasi_init_tp',
  '-C link-arg=--export=__wasm_call_ctors',
].join(' ');

function run(command: string, args: string[], env: NodeJS.ProcessEnv = process.env): void {
  const ran = spawnSync(command, args, { cwd: ROOT, stdio: 'inherit', env });
  if (ran.status !== 0) throw new Error(`${command} ${args.join(' ')} exited ${ran.status ?? 'on a signal'}`);
}

const installed = spawnSync('rustup', ['target', 'list', '--installed'], { encoding: 'utf8' });
if (installed.status !== 0) throw new Error('rustup is needed to add the wasm32-wasip1-threads target');
if (!installed.stdout.split('\n').includes(TARGET)) run('rustup', ['target', 'add', TARGET]);

run('bun', ['run', 'scripts/cargo.ts', 'build', '--release', '--target', TARGET, '--manifest-path', manifest], {
  ...process.env,
  RUSTFLAGS,
});

const wasm = await readFile(built);
const wasmHashed = `avif_planes.${createHash('sha256').update(wasm).digest('hex').slice(0, 12)}.wasm`;
await mkdir(pkg, { recursive: true });
await writeFile(join(pkg, wasmHashed), wasm);
await writeFile(
  join(pkg, 'avif_planes.js'),
  `${forwards}\nexport const avifPlanesUrl = new URL('./${wasmHashed}', import.meta.url).href;\n`,
);
await writeFile(join(pkg, 'avif_planes.d.ts'), `${forwards}\nexport const avifPlanesUrl: string;\n`);
for (const entry of await readdir(pkg)) {
  if (/^avif_planes\.[0-9a-f]{12}\.wasm$/.test(entry) && entry !== wasmHashed) await rm(join(pkg, entry));
}

console.log(`pkg: ${wasmHashed}`);
