// Gives the decoder's built package content-addressed filenames, and points its loader at them.
//
// **A stale module is indistinguishable from a fix that did not work.** `wasm-pack` emits
// `rawshim.js` and `rawshim_bg.wasm` under names that never change, and each build overwrites them
// in place - so a browser, a dev server or a proxy holding a previous one serves it against the
// current source with nothing looking wrong.
//
// Hashed, a name changes whenever a byte does, so an old entry cannot answer for a new build: it is
// not merely unlikely to be cached, it is unaddressable.
//
// The JavaScript keeps a stable `rawshim.js` in front of it, because that one is imported by path
// from TypeScript rather than fetched by URL, and rewriting importers on every build would put
// generated names into source. That entry is two re-export lines - small enough that serving a
// stale copy of it cannot serve stale *code*, since the module it names changes with the build.

import { createHash } from 'node:crypto';
import { readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const pkg = join(import.meta.dir, '..', 'native', 'rawshim', 'pkg');
const wasmPlain = 'rawshim_bg.wasm';
const gluePlain = 'rawshim.js';
const forwards = '// Generated by scripts/hash-pkg.ts.';

const hashOf = (bytes: string | Uint8Array): string =>
  createHash('sha256').update(bytes).digest('hex').slice(0, 12);

const glueBefore = await readFile(join(pkg, gluePlain), 'utf8');
if (glueBefore.startsWith(forwards)) {
  throw new Error(`${gluePlain} is already the forwarding entry; run wasm-pack before this`);
}

// The module first, since the loader names it and so the loader's own bytes depend on it.
const wasm = await readFile(join(pkg, wasmPlain));
const wasmHashed = `rawshim_bg.${hashOf(wasm)}.wasm`;
await writeFile(join(pkg, wasmHashed), wasm);
await rm(join(pkg, wasmPlain), { force: true });

if (!glueBefore.includes(wasmPlain)) {
  throw new Error(`${gluePlain} does not name ${wasmPlain}; wasm-pack's loader has changed shape`);
}
const glue = glueBefore.replaceAll(wasmPlain, wasmHashed);
const glueHashed = `rawshim.${hashOf(glue)}.js`;
await writeFile(join(pkg, glueHashed), glue);

// What TypeScript and Vite resolve `.../pkg/rawshim` to. `export *` does not carry a default, so
// the two lines are not one.
await writeFile(
  join(pkg, gluePlain),
  `${forwards}\nexport * from './${glueHashed}';\nexport { default } from './${glueHashed}';\n`,
);

// Every earlier build's, once this one's are in place: `pkg` is not cleaned between runs, and a
// directory of stale modules is what this exists to stop being reachable.
for (const entry of await readdir(pkg)) {
  const stale =
    (/^rawshim_bg\.[0-9a-f]{12}\.wasm$/.test(entry) && entry !== wasmHashed) ||
    (/^rawshim\.[0-9a-f]{12}\.js$/.test(entry) && entry !== glueHashed);
  if (stale) {
    await rm(join(pkg, entry));
  }
}

// So `files` still describes what is there, for anything reading the package rather than the
// entry. Parsed rather than string-replaced: `main` also spells the plain names, and editing by
// text rewrites it into JSON that no longer parses.
const manifestPath = join(pkg, 'package.json');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as { files?: string[] };
if (!Array.isArray(manifest.files)) {
  throw new Error('pkg/package.json has no files array; wasm-pack has changed shape');
}
manifest.files = manifest.files.map((entry) => (entry === wasmPlain ? wasmHashed : entry));
manifest.files.push(glueHashed);
await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

console.log(`pkg: ${glueHashed}, ${wasmHashed}`);
