import * as stylex from '@stylexjs/stylex';
import { color, size } from '../../../ui/tokens.stylex';

export const styles = stylex.create({
  editor: { paddingTop: '8px' },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '6px',
  },
  heading: { margin: 0, color: color.bone, fontSize: size.controlText, fontWeight: 500 },
  channels: {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, 1fr)',
    gap: '2px',
    marginBottom: '8px',
  },
  channel: {
    position: 'relative',
    minHeight: size.controlH,
    paddingInline: 0,
    border: 'none',
    borderRadius: size.radius,
    backgroundColor: color.field,
    color: color.boneDim,
    fontSize: '11px',
    cursor: 'pointer',
  },
  channelChosen: { backgroundColor: color.slate, color: color.bone },
  dot: {
    position: 'absolute',
    left: '50%',
    bottom: '3px',
    width: '4px',
    height: '4px',
    marginLeft: '-2px',
    borderRadius: '50%',
    backgroundColor: 'transparent',
  },
  dotShown: { backgroundColor: color.satin },
  wheel: {
    position: 'relative',
    width: '100%',
    aspectRatio: '1',
  },
  layer: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
  },
  backdrop: { borderRadius: '50%', backgroundColor: color.field },
  overlay: { overflow: 'visible', touchAction: 'none' },
  disabled: { opacity: 0.4 },
  edge: {
    fill: 'none',
    stroke: color.bone,
    strokeWidth: '1px',
    strokeDasharray: '3 3',
    vectorEffect: 'non-scaling-stroke',
    opacity: 0.7,
    pointerEvents: 'none',
  },
  field: {
    stroke: color.bone,
    strokeWidth: '1px',
    vectorEffect: 'non-scaling-stroke',
    opacity: 0.3,
    pointerEvents: 'none',
  },
  reach: {
    fill: color.bone,
    fillOpacity: 0.08,
    fillRule: 'evenodd',
    stroke: color.bone,
    strokeWidth: '1px',
    vectorEffect: 'non-scaling-stroke',
    pointerEvents: 'none',
  },
  arrow: {
    stroke: color.bone,
    strokeWidth: '2px',
    vectorEffect: 'non-scaling-stroke',
    pointerEvents: 'none',
  },
  head: { fill: color.bone },
  node: {
    r: '0.045px',
    fill: color.ink,
    stroke: color.bone,
    strokeWidth: '2px',
    vectorEffect: 'non-scaling-stroke',
    cursor: 'pointer',
    outline: 'none',
  },
  nodeChosen: { fill: color.satin },
  handle: {
    r: '0.03px',
    fill: color.bone,
    stroke: color.ink,
    strokeWidth: '1px',
    vectorEffect: 'non-scaling-stroke',
    cursor: 'grab',
  },
  target: { r: '0.04px', fill: color.satin },
  hint: { marginTop: '8px' },
  controls: { marginTop: '8px' },
  subheading: { color: color.boneDim, fontSize: '12px' },
  remove: {
    marginTop: '6px',
    paddingBlock: '4px',
    paddingInline: '8px',
    border: 'none',
    borderRadius: size.radius,
    backgroundColor: color.slate,
    color: color.bone,
    cursor: 'pointer',
  },
});
