export const ColourWheelStrings = {
  heading: () => 'Colour edits',
  reset: () => 'Reset colour edits',
  options: () => 'Colour wheel options',
  showDisplayGamut: () => 'Show my display gamut',
  showPhotoColours: () => 'Show photo colours',
  showProfileChanges: () => 'Show colour profile changes',
  wheel: () => 'Colour wheel',
  lightness: () => 'Lightness',
  // A lightness the wheel edits colours at, not the Light panel's tone sliders of the same names.
  shadows: () => 'Shadows',
  darks: () => 'Darks',
  midtones: () => 'Midtones',
  lights: () => 'Lights',
  highlights: () => 'Highlights',
  all: () => 'All',
  channelEdited: (channel: string) => `${channel} (edited)`,
  edit: (hue: number) => `Colour edit at hue ${Math.round(hue)}°`,
  outputColour: () => 'Output colour',
  outputHue: () => 'Output hue',
  outputSaturation: () => 'Output saturation',
  outputLightness: () => 'Output lightness',
  hueRange: () => 'Hue range',
  saturationRange: () => 'Saturation range',
  lightnessRange: () => 'Lightness range',
  remove: () => 'Remove colour edit',
  full: (most: number) => `You can add up to ${most} colour edits.`,
};
