import * as stylex from '@stylexjs/stylex';
import { color, size } from '../../../ui/tokens.stylex';

const COARSE = '@media (pointer: coarse)';

export const styles = stylex.create({
  editor: { paddingTop: '8px' },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '6px',
  },
  heading: { margin: 0, color: color.bone, fontSize: size.controlText, fontWeight: 500 },
  headerActions: { display: 'flex', alignItems: 'center', gap: '4px' },
  channels: {
    display: 'flex',
    justifyContent: 'space-between',
    paddingInline: '4px',
    marginBottom: '12px',
  },
  pot: {
    position: 'relative',
    width: size.controlH,
    height: size.controlH,
    padding: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: color.slate,
    borderRadius: '50%',
    cursor: 'pointer',
    boxShadow: { default: null, ':hover': `0 0 0 2px ${color.slate}` },
  },
  potChosen: { boxShadow: `0 0 0 2px ${color.satin}` },
  shadows: { backgroundColor: '#1b1b1b' },
  darks: { backgroundColor: '#474747' },
  midtones: { backgroundColor: '#848484' },
  lights: { backgroundColor: '#c6c6c6' },
  highlights: { backgroundColor: '#ffffff' },
  all: { backgroundImage: 'linear-gradient(90deg, #1b1b1b, #ffffff)' },
  divider: { width: '1px', alignSelf: 'stretch', backgroundColor: color.slate },
  marks: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: '-8px',
    display: 'flex',
    justifyContent: 'center',
    gap: '2px',
  },
  mark: { width: '4px', height: '4px', borderRadius: '50%' },
  swatch: (colour: string) => ({ backgroundColor: colour }),
  wheel: {
    position: 'relative',
    width: '100%',
    aspectRatio: '1',
  },
  layer: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
  },
  backdrop: { borderRadius: '50%', backgroundColor: color.field },
  overlay: { overflow: 'visible', touchAction: 'pan-y' },
  disabled: { opacity: 0.4 },
  edge: {
    fill: 'none',
    stroke: color.bone,
    strokeWidth: '1px',
    strokeDasharray: '3 3',
    vectorEffect: 'non-scaling-stroke',
    opacity: 0.7,
    pointerEvents: 'none',
  },
  field: {
    stroke: color.bone,
    strokeWidth: '1.5px',
    vectorEffect: 'non-scaling-stroke',
    opacity: 0.55,
    pointerEvents: 'none',
  },
  reach: {
    fill: color.bone,
    fillOpacity: 0.08,
    fillRule: 'evenodd',
    stroke: color.bone,
    strokeWidth: '1px',
    vectorEffect: 'non-scaling-stroke',
    pointerEvents: 'none',
  },
  arrow: {
    stroke: color.bone,
    strokeWidth: '2px',
    vectorEffect: 'non-scaling-stroke',
    pointerEvents: 'none',
  },
  head: { fill: color.bone },
  node: {
    fill: 'transparent',
    stroke: color.bone,
    strokeWidth: '1.5px',
    vectorEffect: 'non-scaling-stroke',
    pointerEvents: 'none',
  },
  nodeChosen: { strokeWidth: '3px' },
  target: {
    fill: 'transparent',
    stroke: color.ink,
    strokeWidth: '1px',
    vectorEffect: 'non-scaling-stroke',
    pointerEvents: 'none',
  },
  grab: {
    r: { default: '0.05px', [COARSE]: '0.14px' },
    fill: 'transparent',
    cursor: 'grab',
    outline: 'none',
  },
  shown: { visibility: 'visible', opacity: 0.5 },
  clipped: (clip: string) => ({ clipPath: clip, visibility: 'visible', opacity: 0.5 }),
  twoWay: {
    fill: 'none',
    stroke: color.bone,
    strokeWidth: '2px',
    strokeLinecap: 'round',
    vectorEffect: 'non-scaling-stroke',
    pointerEvents: 'none',
  },
  fieldHead: { fill: color.bone },
  hint: { marginTop: '8px' },
  controls: { marginTop: '8px' },
  remove: { marginTop: '6px' },
});
