// What a test can ask about pixels, for tests and pins alone.
//
// This replaces `rawshim_pixels.ts`, and the difference is the point: that module
// read samples back into a `Buffer`, which meant the native side had to hand out an
// address and keep it valid across calls. Everything the pins actually assert - that
// two decode routes agree, that a grade is stable, that a decode is scene-referred -
// is a digest or a statistic, and both are cheaper to compute where the pixels
// already are.
//
// Lint keeps this out of `src/**`. It is not a production API and the one door in it
// that does hand bytes over, `dumpDecode`, goes through a file and says so in the log.
import { ptr } from 'bun:ffi';
import { shim } from './rawshim';

export interface ChannelStats {
  min: number;
  max: number;
  mean: number;
}

export interface DecodeSummary {
  width: number;
  height: number;
  depth: number;
  /** Samples, not bytes: a 16-bit frame has half as many as it has bytes. */
  samples: number;
  bytes: number;
  halved: boolean;
  /**
   * Whether the decode came straight out of LibRaw's processed buffer rather than
   * through `dcraw_make_mem_image` (§10.4). The differential pin checks its two arms
   * took different routes; without it a passing comparison proves nothing.
   */
  direct: boolean;
  sha1: string;
  channels: ChannelStats[];
}

export interface Comparison {
  width: number;
  height: number;
  /** Null when the two images are identical, PSNR being infinite there. */
  psnr: number | null;
}

export interface GradedSummary {
  width: number;
  height: number;
  /**
   * SHA-256, not the SHA-1 a decode reports. `hdr_grade.pin.txt` holds SHA-256es
   * generated by the TypeScript this subsystem replaced, and matching the function
   * keeps that pin valid unregenerated - so it still says "unchanged since before the
   * port" rather than "unchanged since the port".
   */
  sha256: string;
  channels: ChannelStats[];
  samples: number[];
  /** The luma quantiles the call asked for, in nits, in the order asked. */
  quantiles: number[];
}

export interface HdrColour {
  deltaE: number;
  saturation: number;
  /** Three 256-entry curves over render values 0 to the trust ceiling. */
  curves: number[][];
  /** Where the SDR fit took the geometry this reuses. */
  distortionSource: 'none' | 'camera' | 'fitted' | 'lensfun';
}

interface DebugReply {
  ok: boolean;
  error?: string;
  reply?: {
    summary?: DecodeSummary;
    written?: number;
    comparison?: Comparison;
    graded?: GradedSummary;
    colour?: HdrColour;
  };
}

// Comfortably past any reply: a summary is a few hundred bytes.
const CAPACITY = 64 * 1024;

function ask(command: Record<string, unknown>): DebugReply['reply'] {
  const bytes = Buffer.from(JSON.stringify(command), 'utf8');
  let out = new Uint8Array(CAPACITY);
  let written = Number(shim().bb_debug(bytes, bytes.byteLength, ptr(out), out.byteLength));
  if (written > out.byteLength) {
    out = new Uint8Array(written);
    written = Number(shim().bb_debug(bytes, bytes.byteLength, ptr(out), out.byteLength));
  }
  if (written < 0) throw new Error('rawshim could not answer the debug command');
  const parsed = JSON.parse(new TextDecoder().decode(out.subarray(0, written))) as DebugReply;
  if (!parsed.ok) throw new Error(parsed.error ?? 'rawshim could not answer the debug command');
  return parsed.reply;
}

export interface DecodeRequest {
  depth?: 8 | 16;
  space?: 'srgb' | 'rec2020-linear';
  atLeastLongEdge?: number;
}

/** A decode, described rather than returned. */
export function decodeSummary(path: string, request: DecodeRequest = {}): DecodeSummary {
  const reply = ask({
    kind: 'decodeSummary',
    path,
    depth: request.depth ?? 8,
    rec2020Linear: request.space === 'rec2020-linear',
    atLeastLongEdge: request.atLeastLongEdge ?? 0,
  });
  if (reply?.summary == null) throw new Error(`no summary for ${path}`);
  return reply.summary;
}

/**
 * A written image against an 8-bit decode of the RAW it came from.
 *
 * The comparison happens where both sets of pixels already are; what comes back is
 * the number the assertion was going to reduce them to anyway.
 */
export function comparePsnr(imagePath: string, rawPath: string): Comparison {
  const reply = ask({ kind: 'comparePsnr', imagePath, rawPath });
  if (reply?.comparison == null) throw new Error(`no comparison for ${imagePath}`);
  return reply.comparison;
}

/** The parts of an HDR encode a pin varies. */
export interface GradeSpec {
  peakNits: number;
  referenceWhiteNits: number;
  whiteQuantile: number;
  crf: number;
  preset: number;
  /**
   * Longest edge, or `Infinity` for the frame's own size - which crosses as null,
   * `JSON.stringify` having no way to write an infinity.
   */
  maxEdge: number;
  stillFullChroma?: boolean;
  outputPath?: string;
}

function gradeArgs(grade: GradeSpec): Record<string, unknown> {
  return { ...grade, maxEdge: Number.isFinite(grade.maxEdge) ? grade.maxEdge : null };
}

/**
 * A graded HDR frame, described.
 *
 * `withMatch` fits the camera's colour the way a job with an SDR rendition does: the
 * SDR fit supplies the geometry and the colour is refitted in the grade's own domain
 * (§10.8.1). Both the decode and that fit are held between calls on the native side,
 * so a pin running five cases pays for them once.
 *
 * `quantiles` are luma quantiles to report, in nits. Ask for none where none are
 * wanted: sorting 24M luma values is the expensive part of the reply.
 */
export function gradedSummary(
  path: string,
  grade: GradeSpec,
  options: { withMatch?: boolean; quantiles?: number[] } = {},
): GradedSummary {
  const reply = ask({
    kind: 'gradedSummary',
    path,
    withMatch: options.withMatch ?? false,
    grade: gradeArgs(grade),
    quantiles: options.quantiles ?? [],
  });
  if (reply?.graded == null) throw new Error(`no grade for ${path}`);
  return reply.graded;
}

/** The fitted HDR colour transform, for the assertions that judge the fit itself. */
export function hdrMatchColour(path: string, grade: GradeSpec): HdrColour {
  const reply = ask({ kind: 'hdrMatchColour', path, grade: gradeArgs(grade) });
  if (reply?.colour == null) throw new Error(`no HDR colour fit for ${path}`);
  return reply.colour;
}

/** One HDR still, encoded to `grade.outputPath`. */
export function encodeHdr(path: string, grade: GradeSpec, withMatch: boolean): void {
  ask({ kind: 'encodeHdr', path, withMatch, grade: gradeArgs(grade) });
}

/**
 * A decode's samples, written to `outPath`, plus its summary.
 *
 * The only way to get pixels out, and it goes through the filesystem on purpose:
 * opening a buffer path for the one test that needs bytes would reopen the thing
 * this whole boundary exists to close. The native side logs a warning every time,
 * so a production call shows up in the logs rather than in a review that did not
 * happen.
 */
export function dumpDecode(path: string, outPath: string, request: DecodeRequest = {}): DecodeSummary {
  const reply = ask({
    kind: 'dumpDecode',
    path,
    depth: request.depth ?? 8,
    rec2020Linear: request.space === 'rec2020-linear',
    atLeastLongEdge: request.atLeastLongEdge ?? 0,
    outPath,
  });
  if (reply?.summary == null) throw new Error(`no summary for ${path}`);
  return reply.summary;
}
